# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13694551525bec5eeb56fb34366c2f797f40c42007912f2ec60fc2a26cabaff3f2e53806f02f09c899116c108977904bf5534815b983942598dd7ec1858868c3

test:
  secret_key_base: 2150800d742430ae7c6e1b90ccb6f480e68ce9ace7b149bc5062fdb29751f0f840adebc233e0d4dd24917f284c95ac48fd4b72edbbeeb9d5f1f0e134f6cc7f47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
